[package]
name = "librqbit_core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
anyhow = "1"
url = "2"
uuid = {version = "1", features = ["v4"]}
log = "0.4"
parking_lot = "0.12"
serde = {version = "1", features=["derive"]}
buffers = {path="../buffers"}
bencode = {path = "../bencode", default-features=false}
clone_to_owned = {path="../clone_to_owned"}