[package]
name = "dht"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["macros", "rt-multi-thread", "net", "sync"]}
tokio-stream = {version = "0.1", features = ["sync"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
hex = "0.4"
bencode = {path = "../bencode", default-features=false}
anyhow = "1"
parking_lot = "0.12"
log = "0.4"
pretty_env_logger = "0.4"
futures = "0.3"
rand = "0.8"
indexmap = "1.7"
directories = "4"

clone_to_owned = {path="../clone_to_owned"}
librqbit_core = {path="../librqbit_core"}

[dev-dependencies]
