name: Test turbo branch

on:
  push:
    branches: [turbo]
  pull_request:
    branches: [turbo]
  schedule: [cron: "40 1 * * *"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test rust ${{ matrix.rust }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v3

      - run: rustup default ${{ matrix.rust }} && rustup update ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --workspace --all-features
